apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: ingestion-api
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ingestion-api
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: ingestion-api
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 200m
                    memory: 128Mi

  - target:
      kind: CronJob
      name: processor
    patch: |
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: processor
      spec:
        schedule: "*/5 * * * *"
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                  - name: processor
                    env:
                      - name: BATCH_SIZE
                        value: "25"

images:
  - name: ingestion-api
    newName: ghcr.io/chetbackiewicz/demo/ingestion-api
    newTag: dev
  - name: processor
    newName: ghcr.io/chetbackiewicz/demo/processor
    newTag: dev
